with constructor
shelfsrdjan/ui-init-setup pull request #1
Opened 2022-06-29 12:34 UTC by Srdjanqwe

2022-06-30 06:01 UTC, UkiWoDao commented on src/test/java/pages/SwagLabsLoginPage.java
> +    {
The java convention is to have the opening braces on the same line as the parameter declaration

2022-06-30 06:02 UTC, UkiWoDao commented on src/test/java/pages/SwagLabsLoginPage.java
> +    public void loginAsStandardUser(String username, String password) {
why is this method public?

2022-06-30 06:03 UTC, UkiWoDao commented on src/test/java/pages/SwagLabsLoginPage.java
> +    }
formatting

2022-06-30 06:04 UTC, UkiWoDao commented on src/test/java/pages/SwagLabsLoginPage.java
> +    public void fetchCredentialsForStandardUser() {
why is this method called "fetchCredentials..."?

2022-06-30 06:07 UTC, UkiWoDao commented on src/test/java/tests/SwagLabsLoginTest.java
> +public class SwagLabsLoginTest
No need for this class to be public. Preferably, use the java conventions for curly brace positions. If you prefer the C#  style, then stick to that convention

2022-06-30 06:29 UTC, UkiWoDao requested changes
1. The app does not compile currently on my machine.
2. Consider having your page object pages public methods return page objects as well. This would allow you to chain calls and also not pass around the driver in your tests more than once
3. In our particular case, it's practically certain that the login would execute very fast. In live projects, the page hosting the login mechanism would be a good candidate for being extended with LoadableComponent<> class, since it would tend to take some time, and get slower over time

2022-07-01 15:26 UTC, shelfsrdjan approved these changes

2022-07-01 15:26 UTC, merged